// src/lib/logo.ts
import { logoUrl as rawLogoUrl } from "@/data/media";
import { resolveUrl } from "@/lib/assets";

/**
 * Resolved logo URL for production. Keep the autogenerated source (rawLogoUrl)
 * in src/data/media.ts untouched; this helper provides a resolved URL at
 * runtime so components can safely use it.
 */
export const logoUrl = resolveUrl(rawLogoUrl) ?? rawLogoUrl;
